# Generated by Django 4.2 on 2024-06-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lession',
            options={'ordering': ['-title'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
