# Generated by Django 4.2 on 2024-06-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_lession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='lession',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата успешного входа'),
        ),
    ]
